-- MySQL Script generated by MySQL Workbench
-- Sun Jun  6 22:03:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Proveedor` VARCHAR(45) NOT NULL,
  `Nit_Proveedor` VARCHAR(45) NOT NULL,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Cantidad_Producto` INT NOT NULL,
  `Presio_Venta` INT NOT NULL,
  `Fecha_Entrega` DATE NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Nombre_Cliente` VARCHAR(45) NOT NULL,
  `Nit_Cliente` VARCHAR(45) NOT NULL,
  `Cantidad_Prod` INT NOT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(145) NOT NULL,
  `Fecha_Adquisicion` DATE NOT NULL,
  `Fecha_Vencimineto` DATE NOT NULL,
  `Presio_Venta` INT NOT NULL,
  `Presio_Compra` INT NOT NULL,
  `stock` INT NULL,
  `Nombre_Proveedor` VARCHAR(45) NULL,
  `Nit_Proveedor` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Ventas_idVenta` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Productos_Proveedor_idx` (`Proveedor_idProveedor` ASC),
  INDEX `fk_Productos_Ventas1_idx` (`Ventas_idVenta` ASC),
  CONSTRAINT `fk_Productos_Proveedor`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Ventas1`
    FOREIGN KEY (`Ventas_idVenta`)
    REFERENCES `mydb`.`Ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
